const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    GET_ALL_USER: ' GET_ALL_USER',
    CREATE_ALL_USERS: ' CREATE_ALL_USERS',
    DELETE_USER: 'DELETE_USER',
    EDIT_USER: 'EDIT_USER',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGIN_OUT: 'USER_LOGIN_OUT',

    CREATE_ALL_PRODUCT: 'CREATE_ALL_PRODUCT',
    GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
    GET_USER: 'GET_USER',
    GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
    CREATE_ORDERS: 'CREATE_ORDERS',
    EDIT_ORDERS: 'EDIT_ORDERS',
    GET_ORDERS_LIST: 'GET_ORDERS_LIST',
    CREATE_USER_DK: 'CREATE_USER_DK',
    EDIT_USER_DK: 'EDIT_USER_DK',
    EDIT_ORDERSLIST_COMPLETE: 'EDIT_ORDERSLIST_COMPLETE'



})

export default actionTypes;